---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB6DRmxAXK6Ot1c9Pn7XnZrceYoeCpwq6GHJB3E+iKD2CuXftCOTsDAbTX9GM0xQ4TfgNwdHgziIcMH6DPjRMm8BowwcMyTwP0vPzPTP0luaOcFVyp08Kj6CYtbZP/K9EaCyi5JyfLy2w3kZptuvEgKcp3u6O9QFnxtNjUmhssoj+iC3BVxAK9KtCUWF+eLPlpkDIyvx3DccI7dDn9mWGtQsnDavsJXt4h57YfadssTOoR5HL+mLbYc/3VPwkmLHSvItvUW6q5ieVu02hOdJeQmZbCreb61tPx1EcquIDkdzc2K9bTAQ3bmRqmq07Fk697JTTPPsf18WUtXuvCxMB1rNvQi9tDnxa+8Y0JjauiLZcDsBcGN2MIlxfSpyog1CpYXWkPutduu5EXbgYFayOPLvSCf33VhQcY6BSfl8d861SIJD+rQ/LiHgTXK6zZ575VeCW1CffJfFiDcZDJAje79QobN3PQ/G5yO+QbgK8rsz7VIwNP2OSGUbdscdH55V7B4keTu2bJPTUs3Qkf7lTyzVyiW0fk0q5MVjd/n1ApOs66Hl42lZ+WR4hQqy6nQP+XHMrmb64cJp6KNNs9iGWLnwlE5hxBGvec5uPDKvCDgumsF5MxT1/6gDnnr693CXQ53pwPYf6NW9IontYc2oacaOtFGGP5REaIq9iCzlqMwNTXHbgkH+QPBTvELcaXtZrCpnWo1K/DhZPf6KYUHtSiR
    admin-user: AgBxgB9cmAMxkypRMT5b5N7T0OLznmKlu02Tk+R32xJwoO/rk6HUzcPcownCQ9ckD2f8o4oFPRUTLyek9ykiZz0pi5euVirpJfcKrQhW4qDIRtjkVmuticl2BuCrdW2MhcyMsc/nRRCqfHBtt+WidZaOvVqSpXuoRxHb6Dk1o3QhEJBZZuQoeBJ5lmoW/7ezUB7B8bRWE24H5JT/mTaYPOwQOyZAK1AxrzHKQN5Ws5JCd2+QuoH6XmvxCiM0YhF3ifhk+wfOYL0FR9hOaPhYq3aMaQZaYzsFzov7xGvlV35Y0bHPdl4bT1K7fS3KFb6fMFqonYHsEmNOQRDn8YoSYtUCIX1Fza1LlSjygN9nPQsi3sfPEMeQ+zSR+nhfnZaUme7sibC7PPiDGvnnKpgBAk60CqSNpPow3c7rW6M5gvn5ek9tt5q4ygxWd704b2MwXqmq66mpXCyxLUhb7rKmkZfJ9fsQS3lkBVuQUv7VrEJi1omR2wq/JIS+o/2xU4OMExDVkFUmNrFCyICUUte2YsTN1C/Lfdm+qNeEVTKAm797Il8yE+n82Ro6+dGyGcXAj+4wxvCaRcKKXQ8E3yw8IDDyAYnXPmvmDnzH66XPTRZ3vdvVTAk6+v7KXGRmShkJ8T/V+o14N7Cnwhhv6W1i7ZN/XBxhrpzxXt6gKC0PbWF7yXVf+lNas7GjuSvW6jJcx45LSKF17Q==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
