apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: interview-app-alerts
  namespace: monitoring
spec:
  groups:
    - name: interview-app.rules
      rules:
        # High CPU alert
        - alert: HighCPUUsage
          expr: sum(rate(container_cpu_usage_seconds_total{namespace="default", pod=~"interview-app.*"}[5m])) by (pod) > 0.8
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} CPU usage is high"
            description: "CPU usage above 80% for more than 2 minutes"

        # High Memory alert
        - alert: HighMemoryUsage
          expr: sum(container_memory_usage_bytes{namespace="default", pod=~"interview-app.*"}) by (pod) > 300000000
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} Memory usage is high"
            description: "Memory usage above 300MB for more than 2 minutes"

        # Pod restart alert
        - alert: PodRestarts
          expr: increase(kube_pod_container_status_restarts_total{namespace="default", pod=~"interview-app.*"}[5m]) > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Pod {{ $labels.pod }} has restarted"
            description: "Pod has restarted in the last 5 minutes"
