apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: interview-app-auth
  namespace: ngrok-operator
spec:
  template:
    type: Opaque
    metadata:
      name: interview-app-auth
      namespace: ngrok-operator
  encryptedData:
    username: AQCbvIxRjy1TJG7fI9hX8lWgYr/xXcz0u7GoqzR0P9Se4JYW/DOjqGP7FqK3Qr2q+2ci898Jp81BC33K1Em2wUR0tINOAqdG06DZo0mfMdkqEUkDdm1FpnofKfMkp9CtmUuzkJRjL2JdSfqYFgqf7VW39S2daMTZqDG23tieKXfQm1bcsF3xjTA3zoPrObhWncthv949ZUDtBHGXucqdSsfbV6ZA0olLfuSeNifhX/lTzEyPfeR4OVj7XM/d4zIe5SUbJm4asXi5K+9FYOJlFgBsWzIV4S/TUUQKrJaBsNHR9rxfs+0wzb1o3ITIAqLFGQeBFaWhk9ci/dkdZ0GcXmKcGC+0Y119P1ilqW39gh8HnwQrJOjV
    password: AQCVVX88RHRjCDH46EiLAqOV2BeELYIIZJoL4e/DGeuqZCb3jSln1lEpE4681/B6/EDgqIoVs+7IwWG3GgNdoNBg4IrQ7JnN35UPpyy/E0Ts2MLEq6wIN97jg38qssomquMDQoLG/NqduqU4G0rhTPWR14Dl50U8sefr6ptXIZfthfRbICoUyFjl1iaNbVc6VCl3LLgO+tNGe3LbYKa/fj6tb4/yDIPcnXGx20GYcjMa5H4kJ55lRzXMjWLTxN8TXcBW2cpf84wtzSyirgFqoUKtYzTtwa/Il3mPlzl31CHU5kcm6WzueCoPtBF2R0MN0sX66e8N15zonGecpOHf5sdV9tw6r3Jv9sqJjSJjK1WgCwD01T5A4DE4v5OScPE=
