name: CI - SonarCloud scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar-scan:
    name: SonarCloud analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history helps Sonar compute metrics

      # If your sonar-project.properties is at the repo root,
      # the action will pick it up automatically.
      - name: Run Sonar (SonarCloud / SonarQube)
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # Optional: if you use SonarQube self-hosted, but for SonarCloud, we set SONAR_HOST_URL
          SONAR_HOST_URL: https://sonarcloud.io
